### ISSUE TITLE
website-ssl.sh: 21: website-ssl.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by shajiquan** [zxlie/website-ssl.sh#2]
运行 `sh website-ssl.sh` 提示如标题。

`21` 行是：

```
function install_config(){
```

环境：
- Ubuntu 14.04.3
- tool_version="1.2"
- GNU bash, version 4.3.11(1)

**Comment by schoeu** [comment]
+1 同样的错误
- debian7
- tool_version="1.2"

**Comment by zxlie** [comment]
``` bash
chmod 0755 website-ssl.sh
./website-ssl.sh
```

**Comment by xiongwilee** [comment]
我用zsh也遇到了同样的问题，是因为sh的兼容问题，这么执行就好了：`sudo bash ./website-ssl.sh`即可
